apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: react-front  
  replicas: 1
  template:
    metadata:
      labels:
        app: react-front  
    spec:
      containers:
      - name: react-front  
        image: jassercherif/react-front:v0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        securityContext:
          runAsNonRoot: true            # Ensures the container does not run as root
          runAsUser: 1000               # Set a non-root user ID
          #readOnlyRootFilesystem: true  # Makes the root filesystem read-only
          allowPrivilegeEscalation: false  # Prevents privilege escalation
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /users
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000
  selector:
    app: react-front